
########################
# Bash-it configuration
########################

source $HOME/.functions
source $HOME/.variables

# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='bobby-python'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='weechat'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Unomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Load Bash It
source $BASH_IT/bash_it.sh

####
# Set vim as the default shell editor
####
VISUAL=vim
EDITOR="$VISUAL"

####
#History size
####
HISTSIZE=100000
HISTFILESIZE=100000

####
# Path
####

export PATH=$PATH:$UTILS/sh:$UTILS/py:$GOPATH/bin:$HOME/.local/bin

####
# Platform specific configuration
####
if [[ "$PLATFORM" == "Darwin" ]]
then
        source $HOME/.bashrc_osx
else
        source $HOME/.bashrc_archlinux
fi

# ####
# # Virtualenv
# ####
# export WORKON_HOME=~/.virtualenvs
# #export VIRTUALENVWRAPPER_SCRIPT=/bin/vitualenvwrapper.sh
# export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
# source /bin/virtualenvwrapper.sh

# ####
# #Dotfiles git repo alias
# ####
# alias config="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"


####
# Copied from .bash_profile
####
# Wallpaper directory

# Override .bash_it/themes/base.theme.bash
function py_interp_prompt {
  py_version=$(python --version 2>&1 | awk '{print " Py-"$2;}') || return
  echo -e "${PYTHON_THEME_PROMPT_PREFIX}${py_version}${PYTHON_THEME_PROMPT_SUFFIX}"
}

# Override .bash_it/themes/colors.theme.bash
function prompt_command() {
    PS1="\n${bold_blue}$(python_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "
}

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Aliases
source $HOME/.aliases

workon devmachine
