# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

####
#History size
####
HISTSIZE=100000
HISTFILESIZE=100000

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

if [ -x /etc/debian_version ]; then
        source $HOME/.bashrc_debian
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export PATH=$PATH:$HOME/.local/bin

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export PATH="${PATH}:${HOME}/.go/bin"
export LC_ALL=en_US.UTF-8

########################
# Rust configuration
########################

export PATH=$PATH:${HOME}/.cargo/bin
source $HOME/.cargo/env

########################
# Bash-it configuration
########################


export PATH=$PATH:$HOME/.local/bin


source $HOME/.functions
source $HOME/.variables

# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='bobby-python'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='weechat'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Unomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)


# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Load Bash It
source $BASH_IT/bash_it.sh

####
# Set vim as the default shell editor
####
VISUAL=nvim
EDITOR="$VISUAL"


####
# Path
####

export GOPATH="$HOME/.go"
export PATH=$PATH:$UTILS/sh:$UTILS/py:$GOPATH/bin:$HOME/.local/bin

#############
# Darwin is no more!
# ####
# # Platform specific configuration
# ####
# if [[ "$PLATFORM" == "Darwin" ]]
# then
#         source $HOME/.bashrc_osx
# else
#         source $HOME/.bashrc_archlinux
# fi

# ####
# # Virtualenv
# ####
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_SCRIPT=/bin/vitualenvwrapper.sh
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
# source /bin/virtualenvwrapper.sh

# ####
# #Dotfiles git repo alias
# ####
# alias config="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"


####
# Copied from .bash_profile
####
# Wallpaper directory

# Override .bash_it/themes/base.theme.bash
function py_interp_prompt {
  py_version=$(python --version 2>&1 | awk '{print " Py-"$2;}') || return
  echo -e "${PYTHON_THEME_PROMPT_PREFIX}${py_version}${PYTHON_THEME_PROMPT_SUFFIX}"
}

# Override .bash_it/themes/colors.theme.bash
function prompt_command() {
    PS1="\n${bold_blue}$(python_version_prompt) ${purple}\h ${reset_color}in ${green}\w\n${bold_cyan}$(scm_char)${green}$(scm_prompt_info) ${green}→${reset_color} "
}

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Aliases
source $HOME/.aliases

# Git branch completion
# if [ -f ~/.git-completion.bash ]; then
#   . ~/.git-completion.bash
# fi

####
# Taskwarrior
####
export TASKWARRIOR_DATA_DIR=$HOME/.task
# task-sync() { repo-sync $TASKWARRIOR_DATA_DIR }

# Latex - NO LATEX FOR YOU!
# export MANPATH=$MANPATH:/usr/local/texlive/2019/texmf-dist/doc/man
# export INFOPATH=$INFOPATH:/usr/local/texlive/2019/texmf-dist/doc/info
# export PATH=$PATH:/usr/local/texlive/2019/bin/x86_64-linux

export NODE_PATH=$HOME/.npm
export $(dbus-launch)
source-completion
