setxkbmap -model pc105 -layout us,il -option grp:win_space_toggle
#### source $HOME/.screenlayout/default2.sh
#### xrdb -load .Xresources
####conky -c ~/.conky/bottom.conky | dzen2 -y 1056 -w 1920 -h 24 &
####exec qtile
feh --bg-scale ~/.wallpapers/*
# status &
# sxhkd &
#### xscreensaver -nosplash&
monitor-config
# exec dwm
xsetroot -cursor_name left_ptr &
exec xmonad
